//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expiration) DeepCopyInto(out *Expiration) {
	*out = *in
	if in.ExpirationDuration != nil {
		in, out := &in.ExpirationDuration, &out.ExpirationDuration
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expiration.
func (in *Expiration) DeepCopy() *Expiration {
	if in == nil {
		return nil
	}
	out := new(Expiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nrql) DeepCopyInto(out *Nrql) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nrql.
func (in *Nrql) DeepCopy() *Nrql {
	if in == nil {
		return nil
	}
	out := new(Nrql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertCondition) DeepCopyInto(out *NrqlAlertCondition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertCondition.
func (in *NrqlAlertCondition) DeepCopy() *NrqlAlertCondition {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrqlAlertCondition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionList) DeepCopyInto(out *NrqlAlertConditionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NrqlAlertCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionList.
func (in *NrqlAlertConditionList) DeepCopy() *NrqlAlertConditionList {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrqlAlertConditionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionObservation) DeepCopyInto(out *NrqlAlertConditionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionObservation.
func (in *NrqlAlertConditionObservation) DeepCopy() *NrqlAlertConditionObservation {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionParameters) DeepCopyInto(out *NrqlAlertConditionParameters) {
	*out = *in
	if in.RunbookURL != nil {
		in, out := &in.RunbookURL, &out.RunbookURL
		*out = new(string)
		**out = **in
	}
	if in.ViolationTimeLimitSeconds != nil {
		in, out := &in.ViolationTimeLimitSeconds, &out.ViolationTimeLimitSeconds
		*out = new(int)
		**out = **in
	}
	if in.Terms != nil {
		in, out := &in.Terms, &out.Terms
		*out = make([]NrqlConditionTerm, len(*in))
		copy(*out, *in)
	}
	out.Nrql = in.Nrql
	in.Signal.DeepCopyInto(&out.Signal)
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = new(Expiration)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.BaselineDirection != nil {
		in, out := &in.BaselineDirection, &out.BaselineDirection
		*out = new(string)
		**out = **in
	}
	if in.AlertsPolicyRef != nil {
		in, out := &in.AlertsPolicyRef, &out.AlertsPolicyRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AlertsPolicySelector != nil {
		in, out := &in.AlertsPolicySelector, &out.AlertsPolicySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionParameters.
func (in *NrqlAlertConditionParameters) DeepCopy() *NrqlAlertConditionParameters {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionSpec) DeepCopyInto(out *NrqlAlertConditionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionSpec.
func (in *NrqlAlertConditionSpec) DeepCopy() *NrqlAlertConditionSpec {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlAlertConditionStatus) DeepCopyInto(out *NrqlAlertConditionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlAlertConditionStatus.
func (in *NrqlAlertConditionStatus) DeepCopy() *NrqlAlertConditionStatus {
	if in == nil {
		return nil
	}
	out := new(NrqlAlertConditionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlConditionTerm) DeepCopyInto(out *NrqlConditionTerm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlConditionTerm.
func (in *NrqlConditionTerm) DeepCopy() *NrqlConditionTerm {
	if in == nil {
		return nil
	}
	out := new(NrqlConditionTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Signal) DeepCopyInto(out *Signal) {
	*out = *in
	if in.AggregationWindow != nil {
		in, out := &in.AggregationWindow, &out.AggregationWindow
		*out = new(int)
		**out = **in
	}
	if in.FillValue != nil {
		in, out := &in.FillValue, &out.FillValue
		*out = new(string)
		**out = **in
	}
	if in.AggregationMethod != nil {
		in, out := &in.AggregationMethod, &out.AggregationMethod
		*out = new(string)
		**out = **in
	}
	if in.AggregationDelay != nil {
		in, out := &in.AggregationDelay, &out.AggregationDelay
		*out = new(int)
		**out = **in
	}
	if in.AggregationTimer != nil {
		in, out := &in.AggregationTimer, &out.AggregationTimer
		*out = new(int)
		**out = **in
	}
	if in.EvaluationOffset != nil {
		in, out := &in.EvaluationOffset, &out.EvaluationOffset
		*out = new(int)
		**out = **in
	}
	if in.EvaluationDelay != nil {
		in, out := &in.EvaluationDelay, &out.EvaluationDelay
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Signal.
func (in *Signal) DeepCopy() *Signal {
	if in == nil {
		return nil
	}
	out := new(Signal)
	in.DeepCopyInto(out)
	return out
}
