// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboard) DeepCopyInto(out *Dashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboard.
func (in *Dashboard) DeepCopy() *Dashboard {
	if in == nil {
		return nil
	}
	out := new(Dashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAreaWidgetConfiguration) DeepCopyInto(out *DashboardAreaWidgetConfiguration) {
	*out = *in
	if in.NRQLQueries != nil {
		in, out := &in.NRQLQueries, &out.NRQLQueries
		*out = make([]DashboardWidgetNRQLQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAreaWidgetConfiguration.
func (in *DashboardAreaWidgetConfiguration) DeepCopy() *DashboardAreaWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardAreaWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardBarWidgetConfiguration) DeepCopyInto(out *DashboardBarWidgetConfiguration) {
	*out = *in
	if in.NRQLQueries != nil {
		in, out := &in.NRQLQueries, &out.NRQLQueries
		*out = make([]DashboardWidgetNRQLQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardBarWidgetConfiguration.
func (in *DashboardBarWidgetConfiguration) DeepCopy() *DashboardBarWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardBarWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardBillboardWidgetConfiguration) DeepCopyInto(out *DashboardBillboardWidgetConfiguration) {
	*out = *in
	if in.NRQLQueries != nil {
		in, out := &in.NRQLQueries, &out.NRQLQueries
		*out = make([]DashboardWidgetNRQLQuery, len(*in))
		copy(*out, *in)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]DashboardBillboardWidgetThreshold, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardBillboardWidgetConfiguration.
func (in *DashboardBillboardWidgetConfiguration) DeepCopy() *DashboardBillboardWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardBillboardWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardBillboardWidgetThreshold) DeepCopyInto(out *DashboardBillboardWidgetThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardBillboardWidgetThreshold.
func (in *DashboardBillboardWidgetThreshold) DeepCopy() *DashboardBillboardWidgetThreshold {
	if in == nil {
		return nil
	}
	out := new(DashboardBillboardWidgetThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLineWidgetConfiguration) DeepCopyInto(out *DashboardLineWidgetConfiguration) {
	*out = *in
	if in.NRQLQueries != nil {
		in, out := &in.NRQLQueries, &out.NRQLQueries
		*out = make([]DashboardWidgetNRQLQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLineWidgetConfiguration.
func (in *DashboardLineWidgetConfiguration) DeepCopy() *DashboardLineWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardLineWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardList) DeepCopyInto(out *DashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardList.
func (in *DashboardList) DeepCopy() *DashboardList {
	if in == nil {
		return nil
	}
	out := new(DashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardMarkdownWidgetConfiguration) DeepCopyInto(out *DashboardMarkdownWidgetConfiguration) {
	*out = *in
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardMarkdownWidgetConfiguration.
func (in *DashboardMarkdownWidgetConfiguration) DeepCopy() *DashboardMarkdownWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardMarkdownWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardObservation) DeepCopyInto(out *DashboardObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardObservation.
func (in *DashboardObservation) DeepCopy() *DashboardObservation {
	if in == nil {
		return nil
	}
	out := new(DashboardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPage) DeepCopyInto(out *DashboardPage) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Widgets != nil {
		in, out := &in.Widgets, &out.Widgets
		*out = make([]DashboardWidget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPage.
func (in *DashboardPage) DeepCopy() *DashboardPage {
	if in == nil {
		return nil
	}
	out := new(DashboardPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardParameters) DeepCopyInto(out *DashboardParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Pages != nil {
		in, out := &in.Pages, &out.Pages
		*out = make([]DashboardPage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardParameters.
func (in *DashboardParameters) DeepCopy() *DashboardParameters {
	if in == nil {
		return nil
	}
	out := new(DashboardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPieWidgetConfiguration) DeepCopyInto(out *DashboardPieWidgetConfiguration) {
	*out = *in
	if in.NRQLQueries != nil {
		in, out := &in.NRQLQueries, &out.NRQLQueries
		*out = make([]DashboardWidgetNRQLQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPieWidgetConfiguration.
func (in *DashboardPieWidgetConfiguration) DeepCopy() *DashboardPieWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardPieWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpec) DeepCopyInto(out *DashboardSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpec.
func (in *DashboardSpec) DeepCopy() *DashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardStatus) DeepCopyInto(out *DashboardStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardStatus.
func (in *DashboardStatus) DeepCopy() *DashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTableWidgetConfiguration) DeepCopyInto(out *DashboardTableWidgetConfiguration) {
	*out = *in
	if in.NRQLQueries != nil {
		in, out := &in.NRQLQueries, &out.NRQLQueries
		*out = make([]DashboardWidgetNRQLQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTableWidgetConfiguration.
func (in *DashboardTableWidgetConfiguration) DeepCopy() *DashboardTableWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardTableWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardWidget) DeepCopyInto(out *DashboardWidget) {
	*out = *in
	in.Configuration.DeepCopyInto(&out.Configuration)
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	out.Layout = in.Layout
	if in.RawConfiguration != nil {
		in, out := &in.RawConfiguration, &out.RawConfiguration
		*out = new(string)
		**out = **in
	}
	out.Visualization = in.Visualization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardWidget.
func (in *DashboardWidget) DeepCopy() *DashboardWidget {
	if in == nil {
		return nil
	}
	out := new(DashboardWidget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardWidgetConfiguration) DeepCopyInto(out *DashboardWidgetConfiguration) {
	*out = *in
	if in.Area != nil {
		in, out := &in.Area, &out.Area
		*out = new(DashboardAreaWidgetConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Bar != nil {
		in, out := &in.Bar, &out.Bar
		*out = new(DashboardBarWidgetConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Billboard != nil {
		in, out := &in.Billboard, &out.Billboard
		*out = new(DashboardBillboardWidgetConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Line != nil {
		in, out := &in.Line, &out.Line
		*out = new(DashboardLineWidgetConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Markdown.DeepCopyInto(&out.Markdown)
	if in.Pie != nil {
		in, out := &in.Pie, &out.Pie
		*out = new(DashboardPieWidgetConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(DashboardTableWidgetConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardWidgetConfiguration.
func (in *DashboardWidgetConfiguration) DeepCopy() *DashboardWidgetConfiguration {
	if in == nil {
		return nil
	}
	out := new(DashboardWidgetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardWidgetLayout) DeepCopyInto(out *DashboardWidgetLayout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardWidgetLayout.
func (in *DashboardWidgetLayout) DeepCopy() *DashboardWidgetLayout {
	if in == nil {
		return nil
	}
	out := new(DashboardWidgetLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardWidgetNRQLQuery) DeepCopyInto(out *DashboardWidgetNRQLQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardWidgetNRQLQuery.
func (in *DashboardWidgetNRQLQuery) DeepCopy() *DashboardWidgetNRQLQuery {
	if in == nil {
		return nil
	}
	out := new(DashboardWidgetNRQLQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardWidgetVisualization) DeepCopyInto(out *DashboardWidgetVisualization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardWidgetVisualization.
func (in *DashboardWidgetVisualization) DeepCopy() *DashboardWidgetVisualization {
	if in == nil {
		return nil
	}
	out := new(DashboardWidgetVisualization)
	in.DeepCopyInto(out)
	return out
}
