apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-newrelic
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/provider-newrelic
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The NewRelic Crossplane provider enables management for NewRelic Services.
    meta.crossplane.io/readme: |
      `provider-newrelic` is the Crossplane provider for
      [NewRelic](https://www.newrelic.com/). Available resources and their
      fields can be found in the [CRD
      Docs](https://marketplace.upbound.io/providers/smcavallo/provider-newrelic).
